# Unit 23. 2차원 리스트 사용하기

## 23.1 2차원 리스트를 만들고 요소에 접근하기

In [ ]:
a = [[10, 20], 
     [30, 40], 
     [50, 60]]
print(a)

[[10, 20], [30, 40], [50, 60]]


In [ ]:
## 23.1.1  2차원 리스트의 요소에 접근하기 (a[행인덱스][[열인덱스]])
a = [[10, 20], 
     [30, 40], 
     [50, 60]]

print(a[1][0])
a[1][1] = 100
print(a)

30
[[10, 20], [30, 100], [50, 60]]


In [ ]:
import numpy as np
b = np.arange(16).reshape(4,4)
print(b)
print(b[1, 1])
print(b[1:-1,1:-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
5
[[ 5  6]
 [ 9 10]]


In [ ]:
## 참고 : 톱니형 리스트 
a = [[10, 20],
     [500, 600, 700],
     [9],
     [30, 40],
     [8],
     [800, 900, 1000]]

print(a)

[[10, 20], [500, 600, 700], [9], [30, 40], [8], [800, 900, 1000]]


In [ ]:
## 참고 
a = []
for i in range(4):
  t = []
  for k in range(4):
    t.append(i*4+k)
  a.append(t)

print(a)

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]


In [ ]:
## 참고 : 사람이 알아보기 쉽게 출력하기
a = [[10, 20], 
     [30, 40], 
     [50, 60]]

print(a)

from pprint import pprint
pprint(a, indent = 4, width = 20)   # indent : 들여쓰기 칸 수, width : 가로폭

[[10, 20], [30, 40], [50, 60]]
[   [10, 20],
    [30, 40],
    [50, 60]]


## 23.2 반복문으로 2차원 리스트의 요소를 모두 출력하기

In [ ]:
## 23.2.1  for 반복문을 한 번만 사용하기
a = [[10, 20], [30, 40], [50, 60]]

for x, y in a:
  print(x, y)

10 20
30 40
50 60


In [ ]:
## 23.2.2  for 반복문을 두 번 사용하기
a = [[10, 20], [30, 40], [50, 60]]

for i in a:
  for j in i:
    print(j, end =' ')
  print()

10 20 
30 40 
50 60 


In [ ]:
## 23.2.3  for와 range 사용하기
a = [[10, 20], [30, 40], [50, 60]]

for i in range(len(a)):
  for j in range(len(a[i])):
    print(a[i][j], end =' ')
  print()

10 20 
30 40 
50 60 


## 23.7 심사문제 : 지뢰찾기
표준 입력으로 2차원 리스트의 가로(col)와 세로(row)가 입력되고 그 다음 줄부터 리스트의 요소로 들어갈 문자가 입력됩니다. 이때 2차원 리스트 안에서 *는 지뢰이고 .은 지뢰가 아닙니다. 지뢰가 아닌 요소에는 인접한 지뢰의 개수를 출력하는 프로그램을 만드세요(input에서 안내 문자열은 출력하지 않아야 합니다).

여러 줄을 입력 받으려면 다음과 같이 for 반복문에서 input을 호출한 뒤 append로 각 줄을 추가하면 됩니다(list 안에 문자열을 넣으면 문자열이 문자 리스트로 변환됩니다).

```
matrix = [] 
for i in range(row):
    matrix.append(list(input()))
```



In [9]:
import random
mines = []
for _ in range(9):
  row = ''
  for _ in range(9):
    if random.random() > 0.6 :
      row += "*"
    else :
      row += '.'
  mines.append(row)

In [10]:
def print_matrix(mat):
  for i in range(len(mat)):
    for k in range(len(mat)):
      print(mat[i][k], end=' ')
    print()

print_matrix(mines)

. . * * . . . . . 
. . . . * . * . . 
* * * . . . * . . 
* * . . . * . . . 
. . . . . . * . * 
* . . * . * . * . 
* . * . . . * . . 
* * . . * * . * . 
* * . * * . . * . 


In [13]:
pad_mines = []
pad_mines.append('............')
for i in range(9):
  row = '.'
  for k in range(9):
    row += mines[i][k]
  row += '.'
  pad_mines.append(row)
pad_mines.append('............')
print_matrix(pad_mines)

. . . . . . . . . . . 
. . . * * . . . . . . 
. . . . . * . * . . . 
. * * * . . . * . . . 
. * * . . . * . . . . 
. . . . . . . * . * . 
. * . . * . * . * . . 
. * . * . . . * . . . 
. * * . . * * . * . . 
. * * . * * . . * . . 
. . . . . . . . . . . 


In [17]:
final_mines = []

for i in range(1, 10):
  row = ''
  for k in range(1,10):
    if pad_mines[i][k] == '*':
      row += '*'
    else:
      count = (pad_mines[i-1][k-1]=="*")  + (pad_mines[i-1][k]=='*')+\
              (pad_mines[i-1][k+1]=="*") + (pad_mines[i][k-1]=='*')+\
              (pad_mines[i][k+1]=="*") + (pad_mines[i+1][k-1]=='*')+\
              (pad_mines[i+1][k]=="*") + (pad_mines[i+1][k+1]=='*')
      row += str(count)
  final_mines.append(row)

print_matrix(final_mines)

0 1 * * 2 2 1 1 0 
2 4 4 4 * 3 * 2 0 
* * * 2 2 4 * 2 0 
* * 3 1 1 * 3 3 1 
3 3 2 1 3 3 * 3 * 
* 3 2 * 2 * 4 * 2 
* 5 * 3 4 4 * 3 2 
* * 4 4 * * 4 * 2 
* * 3 * * 3 3 * 2 


In [51]:
row, col = map(int, input().split())
matrix = []
for i in range(row):
    matrix.append(list(input()))
print()
for i in range(row):
    for j in range(col):
        cnt = 0
        if matrix[i][j] == ".":
            if i != 0 and j != 0: 
                if matrix[i-1][j-1] == "*": cnt += 1
            if i != row-1 and j != col-1:
                if matrix[i+1][j+1] == "*": cnt += 1
            if i != 0:
                if matrix[i-1][j] == "*": cnt += 1
            if i != 0 and j != col-1:
                if matrix[i-1][j+1] == "*": cnt += 1
            if j != 0:
                if matrix[i][j-1] == "*": cnt += 1
            if i != row - 1 and j != 0:
                if matrix[i+1][j-1] == "*": cnt += 1
            if j != col -1:
                if matrix[i][j+1] == "*": cnt += 1
            if i != row -1:
                if matrix[i+1][j] =="*": cnt += 1
            matrix[i][j] = cnt
            print(matrix[i][j], end="")
        else:
            print(matrix[i][j], end="")
    print()

3 3
.**
*..
.*.

2**
*43
2*1


8