In [10]:
import numpy as np

a = np.random.randn(5)

print(a)
print(a.shape)

[ 0.69796661 -0.3852809  -0.76640886 -1.1543095  -0.17340509]
(5,)


In [11]:
print(a.T)
print(a.T.shape)
# a와 a.T의 구조가 동일한 것을 확인 할 수 있음

[ 0.69796661 -0.3852809  -0.76640886 -1.1543095  -0.17340509]
(5,)


In [14]:
print(np.dot(a, a.T)) # 값을 하나만 출력

2.585481036594212


In [15]:
a = np.random.randn(5, 1)

print(a)
print(a.shape)

[[-0.68034765]
 [ 0.68538817]
 [ 1.9233162 ]
 [ 0.39838338]
 [-0.70388864]]
(5, 1)


In [16]:
print(a.T)
print(a.T.shape)

[[-0.68034765  0.68538817  1.9233162   0.39838338 -0.70388864]]
(1, 5)


In [18]:
print(np.dot(a, a.T)) # 5*5의 행렬로 출력

[[ 0.46287292 -0.46630223 -1.30852365 -0.27103919  0.47888898]
 [-0.46630223  0.46975694  1.31821817  0.27304725 -0.48243694]
 [-1.30852365  1.31821817  3.69914522  0.76621721 -1.35380043]
 [-0.27103919  0.27304725  0.76621721  0.15870932 -0.28041753]
 [ 0.47888898 -0.48243694 -1.35380043 -0.28041753  0.49545922]]


In [ ]:
# 결론적으로,
a = np.random.randn(5)      # 은 사용하지 말고
a = np.random.randn(5, 1)   # 사용(column vector)
a = np.random.randn(1, 5)   # 사용(row vector)